name: 'CryptoGuard-Go Security Scan'
description: 'Scan Go code for cryptographic misuse'

inputs:
  path:
    description: 'Package path'
    default: './...'
  severity:
    description: 'Minimum severity'
    default: 'medium'
  fail-on-findings:
    description: 'Fail if issues found'
    default: 'true'

runs:
  using: 'composite'
  steps:
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    - shell: bash
      run: go install github.com/ravisastryk/cryptoguard-go/cmd/cryptoguard@latest
    - shell: bash
      run: cryptoguard -format sarif -severity ${{ inputs.severity }} ${{ inputs.path }} > cryptoguard-results.sarif || true
    - uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: cryptoguard-results.sarif
    - shell: bash
      run: |
        COUNT=$(jq '.runs[0].results | length' cryptoguard-results.sarif 2>/dev/null || echo "0")
        echo "findings-count=$COUNT" >> $GITHUB_OUTPUT
        if [ "${{ inputs.fail-on-findings }}" == "true" ] && [ "$COUNT" -gt "0" ]; then
          echo "::error::CryptoGuard found $COUNT issues"; exit 1
        fi
